In [1]:
import numpy as np
print("imported")

imported


In [2]:
np.array(1)
print(type(np.array(1)))

<class 'numpy.ndarray'>


In [8]:
arr = np.array([[1,2,3,4,5],[6,7,5,8,4]])
print(arr)

[[1 2 3 4 5]
 [6 7 5 8 4]]


In [9]:
len(arr)

2

In [ ]:
#attributes
print(arr.shape)
print(arr.ndim)
print(arr.size)


(2, 5)
2
10


In [15]:
#method
print(np.arange(0,10))
print(np.random.rand(3,4))

[0 1 2 3 4 5 6 7 8 9]
[[0.1244453  0.73293923 0.49986965 0.38199785]
 [0.05194921 0.02283251 0.36848527 0.97240384]
 [0.65040085 0.58404168 0.43575562 0.5209844 ]]


In [ ]:
np.random.randint(0,10,10) # start end  size

array([4, 9, 4, 2, 8, 7, 6, 8, 7, 2], dtype=int32)