In [2]:
import numpy as np
print("imported")

imported


In [3]:
np.array(1)
print(type(np.array(1)))

<class 'numpy.ndarray'>


In [4]:
arr = np.array([[1,2,3,4,5],[6,7,5,8,4]])
print(arr)

[[1 2 3 4 5]
 [6 7 5 8 4]]


In [5]:
len(arr)

2

In [6]:
#attributes
print(arr.shape)
print(arr.ndim)
print(arr.size)


(2, 5)
2
10


In [7]:
#method
print(np.arange(0,10))
print(np.random.rand(3,4))

[0 1 2 3 4 5 6 7 8 9]
[[0.06033727 0.43837744 0.7247963  0.90835531]
 [0.19414638 0.63360899 0.60786077 0.11587598]
 [0.64849479 0.52378362 0.570638   0.45499794]]


In [8]:
np.random.randint(0,10,10) # start end  size

array([0, 2, 5, 2, 4, 3, 1, 8, 8, 6], dtype=int32)

In [13]:
#zeros
np.zeros((2,4 ,2),dtype=int) #no. matrix , rows , cols 

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [12]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [21]:
#min , max,argmax , argmin
print(arr)

arr.ravel()
arr = arr.flatten()
#min
#py method 
min(arr)
#np method
np.min(arr)

#index finding
np.argmax(arr)

#

[1 2 3 4 5 6 7 5 8 4]


np.int64(8)

In [25]:
#mean std
arr+arr   #add

list1 = [1,2,3,4,5]
list1+list1  #concat

arr.mean()
arr.std()

np.float64(2.0615528128088303)